/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chat;

import java.net.*;
import java.io.*; 
import javax.swing.DefaultListModel;
import javax.swing.JList;


/**
 *
 * @author Hugo
 */
public class FApp_IAChat extends javax.swing.JFrame {
    public static int POST_QUESTION = 1;
    public static int ANSWER_QUESTION = -1;
    public static int POST_EVENT = 0;
    public static int EVENT_JOIN = 1;
    public static int EVENT_LEAVE = 2;

    static int msgNum = 0;

    static private String nomCli = "test";
    static private InetAddress adresseGroupe;
    static MulticastSocket socketGroupe;
    static ThreadReception thr;

    static private int port = 5001;
    //static private String address = "234.5.5.9";

    
    /**
     * Creates new form FApp_IAChat
     */
    public FApp_IAChat() {
        initComponents();
        jListMsg.setModel(new DefaultListModel<String>());
    }
    public FApp_IAChat(String nom, String add, int po) {
        initComponents();
        jListMsg.setModel(new DefaultListModel<String>());
        
        try {
            adresseGroupe = InetAddress.getByName(add);
            socketGroupe = new MulticastSocket(port = po);
            socketGroupe.joinGroup(adresseGroupe);

            thr = new ThreadReception (nomCli = nom, socketGroupe, jListMsg);
            thr.start();

            jLabelAccount.setText(nomCli);
            String msgDeb = "<"+ POST_EVENT +">["+ EVENT_JOIN +"]";
            DatagramPacket dtg = new DatagramPacket(msgDeb.getBytes(), msgDeb.length(), adresseGroupe, port);
            socketGroupe.send(dtg);
        }
        catch (UnknownHostException e){ System.out.println("Erreur :-( : " + e.getMessage()); }
        catch (IOException e){ System.out.println("Erreur :-( : " + e.getMessage()); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMsg = new javax.swing.JTextPane();
        jButtonLeave = new javax.swing.JButton();
        jLabelAccount = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListMsg = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextMsg.setToolTipText("Enter your message here");
        jScrollPane1.setViewportView(jTextMsg);

        jButtonLeave.setText("Disconnect");
        jButtonLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveActionPerformed(evt);
            }
        });

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jListMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMsgMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListMsg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLeave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSend)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLeave)
                    .addComponent(jLabelAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveActionPerformed
        String msg = "<"+ POST_EVENT +">["+ EVENT_LEAVE +"]";
        DatagramPacket dtg = new DatagramPacket(msg.getBytes(), msg.length(), adresseGroupe, port);
        try {
            socketGroupe.send(dtg);
            thr.stop();

            socketGroupe.leaveGroup(adresseGroupe); System.out.println("Après leaveGroup");

            socketGroupe.close(); System.out.println("Après close");
        } catch (IOException e) {
            System.out.println("Erreur :-( : " + e.getMessage());
        }
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonLeaveActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        String msg = null;
        if(msgNum == 0)
            msg = "<"+ (Math.round(Math.random() * 98) + 1) +"> "+ jTextMsg.getText();
        else if (msgNum <= ANSWER_QUESTION)
            msg = "<"+ msgNum +"> "+ jTextMsg.getText();

            System.out.println("tdsfdfsfrete " + msg);
        DatagramPacket dtg = new DatagramPacket(msg.getBytes(), msg.length(), adresseGroupe, port);
        try {
            socketGroupe.send(dtg);
            jTextMsg.setText("");
            msgNum = 0;
            jLabelAccount.setText(nomCli);
        } catch (IOException e) {
            System.out.println("Erreur :-( : " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jListMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMsgMouseClicked
        if(evt.getClickCount() == 2) {
            String msg = ((JList)evt.getSource()).getSelectedValue().toString();

            msgNum = Integer.parseInt(msg.substring(msg.indexOf("<")+1, msg.indexOf(">"))) * -1;
            jLabelAccount.setText(nomCli + "  -  " + msgNum * -1);
        }
    }//GEN-LAST:event_jListMsgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FApp_IAChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FApp_IAChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FApp_IAChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FApp_IAChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FApp_IAChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeave;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelAccount;
    private javax.swing.JList<String> jListMsg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextMsg;
    // End of variables declaration//GEN-END:variables
}
